# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  mailer_password: PLAN$rodROCZny
  secret_key_base: 167a575d1fe132ff45e04378288ef529d926a5f4fbfa995cdb5b5c50292d4b65b64b8df464bd6f3f4c28763b9f0d9b3cd0ba10b00fa7affe8a63fa7875a777d2

test:
  mailer_password: PLAN$rodROCZny
  secret_key_base: 3427d70439061ca250a890be15021a06608d7851f181063aed8cf55f7283de68fe1735b9897f496e8f0e84983414deb2ea464c0ba7fa3528c20baa6d6779142d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  mailer_password: PLAN$rodROCZny
  secret_key_base: 5bee5f102387bcaf722d7dfd9734ce0e0813d7a55582b106438e1ac9318aa6f2abb061a383b6269720a9d6319d0cd50a65f77a265d868c21eb6a39cf01a131a6
# Be sure to restart your server when you modify this file.
